Sprint 3
artbuzzon/middle.messenger.praktikum.yandex pull request #3
Opened 2021-05-04 15:29 UTC by artbuzzon

2021-05-06 10:56 UTC, roastedfrost requested changes
Следует исправить (это из чеклиста к проекту)
Нет защиты от XSS, DOS
Нет рабочих тестов
```
> chat@1.0.0 test
> ./node_modules/.bin/mocha

  0 passing (1ms)
```

c линтингом беда-беда, следует причесать

```
>>> ./node_modules/.bin/eslint ./src  

✖ 535 problems (372 errors, 163 warnings)
  345 errors and 0 warnings potentially fixable with the `--fix` option.
```

Работу с сокетом можно сильно улучшить, если инкапсулировать все низкоуровневые вещи (а не только его инстанцирование), например реконект в случае ошибки соединения

2021-05-09 09:10 UTC, artbuzzon commented
@roastedfrost Привет! 
Пишу здесь, т.к. у симулятора, видимо, майские праздники и он уехал на шашлыки.
Добавил тесты и xss. Проверь, плиз 
Спасибо, за комментарий про сокеты - посмотрю как можно улучшить.

2021-05-09 16:05 UTC, roastedfrost reviewed
Сильно лучше, но не хватает защиты от XSS в форме отправки сообщения
(на самом деле лучше перестраховаться и сделать как при отправке с фронта, так и при получении с сервера)

если отправить такое из формы сообщения
```html
<img src="https://www.gravatar.com/avatar/13df883fb1c26b651a89200c3cc3b989?s=32&amp;d=identicon&amp;r=PG&amp;f=1" alt="" onload="console.log('Hello from XSS')">
```
то будет выполняться скрипт при открытии страницы (console.log)

плюс не хватает защиты от DOS
я бы предложил минимальное решение в модуле HTTP.ts, метод _request_
добавить таймер на 200ms-300ms, и если вызвался следующий _request_ до истечения таймера предыдущего, то возвращать `Promise.reject()`, если после истечения - то всё ок и взводится новый таймер

2021-05-09 16:05 UTC, roastedfrost commented on src/components/Input/input.ts
> +import Block from '../../utils/Block';import Baki from '../../utils/Baki';import DOMWorker from '../../utils/DOMWorker';import Valuyadator from '../../utils/Валядатор';interface Options {    [k
что-то здесь страшное произошло 0_о

2021-05-09 16:05 UTC, roastedfrost commented on src/pages/Chat/chat.ts
> +                                    this.socket = getSocketConnection(userId, chatId, token);
какие-то проблемы с форматированием (

2021-05-09 16:05 UTC, roastedfrost commented on src/pages/Profile/index.ts
> +            }
такие конструкции вполне можно развернуть в
```
if (...) {

} else if (...) {

} else if (...) {

}
```
вложенность ни к чему

2021-05-10 09:11 UTC, roastedfrost approved these changes

2021-05-24 06:50 UTC, merged